import {test} from 'node:test';import assert from 'node:assert/strict';
import {seed} from '../seed.mjs';import {edit,risk,sync,resolve,MockCalendar,externalId,add,workdays} from '../core.mjs';
const id='atlas-sample-1';
function linked(){const s=seed(),a=new MockCalendar(s.events);edit(s,id,{start:'2054-10-01'});sync(s,a);return [s,a];}
test('task state transitions, version and queue coalescing',()=>{const s=seed();for(const status of ['DOING','REVIEW','DONE'])edit(s,id,{status});assert.equal(s.tasks[0].version,4);assert.deepEqual(s.queue,[id]);assert.equal(s.audit.length,3);assert.throws(()=>edit(s,id,{status:'BAD'}));});
test('date controls and Gantt shift edit the same ID and preserve duration',()=>{const s=seed(),t=s.tasks[0],original=t.id;edit(s,id,{start:add(t.start,3),end:add(t.end,3)});assert.equal(t.id,original);assert.equal(s.tasks.length,5);assert.equal(t.start,'2054-10-03');assert.equal(t.end,'2054-10-05');assert.deepEqual(s.queue,[id]);assert.throws(()=>edit(s,id,{start:'2054-12-01'}));assert.throws(()=>edit(s,id,{start:'2054-02-30'}));});
test('dependencies reject cycles and cross-project IDs',()=>{const s=seed();assert.throws(()=>edit(s,id,{dependencies:['atlas-sample-2']}),/cycle/);assert.throws(()=>edit(s,id,{dependencies:['absent']}));});
test('risk explains overdue, remaining work, blocked dependencies and release slack',()=>{const s=seed(),t=s.tasks[0];assert.equal(risk(t,s.tasks,'2054-10-04').level,'at_risk');assert.ok(risk(t,s.tasks,'2054-10-04').reasons.includes('期限超過'));t.blocker='';t.remaining=1;t.end='2054-10-15';assert.equal(risk(t,s.tasks,'2054-09-30').level,'on_track');t.remaining=100;assert.equal(risk(t,s.tasks,'2054-09-30').level,'at_risk');t.remaining=1;t.blocker='decision';assert.equal(risk(t,s.tasks,'2054-09-30').level,'watch');t.end='2054-11-03';assert.ok(risk(t,s.tasks,'2054-09-30').reasons.includes('リリース目標を超過'));assert.equal(risk(s.tasks[1],s.tasks,'2054-09-30').level,'at_risk');t.status='DONE';assert.equal(risk(t,s.tasks,'2055-01-01').level,'on_track');assert.equal(workdays('2054-10-02','2054-10-05'),2);});
test('initial synchronization and repeated retries do not duplicate or mutate unrelated events',()=>{const [s,a]=linked(),snapshot=structuredClone(s.events);for(let i=0;i<3;i++)sync(s,a);assert.deepEqual(s.events,snapshot);assert.equal(Object.keys(s.events).length,2);assert.equal(s.events[externalId(id)].end,'2054-10-03');assert.equal(s.queue.length,0);});
test('calendar-only changes import once without echo',()=>{const [s,a]=linked(),event=a.read(externalId(id));a.update(event.id,{start:'2054-10-05',end:'2054-10-08'},event.etag);sync(s,a);assert.equal(s.tasks[0].start,'2054-10-05');assert.equal(s.tasks[0].end,'2054-10-07');const version=s.tasks[0].version,etag=a.read(event.id).etag;sync(s,a);assert.equal(s.tasks[0].version,version);assert.equal(a.read(event.id).etag,etag);assert.deepEqual(s.queue,[]);});
test('simultaneous changes conflict, calendar resolution retains board status',()=>{const [s,a]=linked(),e=a.read(externalId(id));edit(s,id,{end:'2054-10-04',status:'REVIEW'});a.update(e.id,{start:'2054-10-05',end:'2054-10-08'},e.etag);sync(s,a);assert.ok(s.conflicts[id]);assert.equal(s.tasks[0].end,'2054-10-04');resolve(s,id,'calendar',a);assert.equal(s.tasks[0].end,'2054-10-07');assert.equal(s.tasks[0].status,'REVIEW');assert.equal(s.conflicts[id],undefined);});
test('board conflict resolution uses current etag and refuses stale decisions',()=>{const [s,a]=linked(),e=a.read(externalId(id));edit(s,id,{end:'2054-10-04'});a.update(e.id,{start:'2054-10-05',end:'2054-10-08'},e.etag);sync(s,a);a.update(e.id,{end:'2054-10-09'},'2');assert.throws(()=>resolve(s,id,'board',a));sync(s,a);resolve(s,id,'board',a);assert.equal(a.read(e.id).end,'2054-10-05');assert.equal(s.conflicts[id],undefined);});
test('unrelated ownership, deleted links and wrong calendars fail closed',()=>{const [s,a]=linked(),e=a.read(externalId(id));s.events[e.id].owner='someone-else';edit(s,id,{end:'2054-10-04'});const before=structuredClone(s.events);sync(s,a);assert.deepEqual(s.events,before);assert.ok(s.conflicts[id]);assert.throws(()=>resolve(s,id,'board',a));delete s.events[e.id];sync(s,a);assert.equal(s.events[e.id],undefined);a.calendarId='production';assert.throws(()=>sync(s,a),/disabled/);});
test('CAS race does not acknowledge failed write and retry reconciles',()=>{const [s,a]=linked();edit(s,id,{end:'2054-10-04'});a.update=()=>{throw Error('ETAG_CONFLICT');};sync(s,a);assert.ok(s.conflicts[id]);assert.deepEqual(s.queue,[id]);sync(s,new MockCalendar(s.events));assert.deepEqual(s.queue,[]);assert.equal(s.events[externalId(id)].end,'2054-10-05');});
test('lost initial acknowledgement recovers using deterministic event ID',()=>{const s=seed(),a=new MockCalendar(s.events);edit(s,id,{end:'2054-10-04'});const original=a.create.bind(a);a.create=e=>{original(e);throw Error('NETWORK_LOST');};sync(s,a);assert.equal(s.queue.length,1);sync(s,new MockCalendar(s.events));assert.equal(Object.keys(s.events).length,2);assert.equal(s.queue.length,0);});
test('invalid remote calendar dates are quarantined',()=>{const [s,a]=linked(),e=a.read(externalId(id));a.update(e.id,{start:'bad'},e.etag);sync(s,a);assert.ok(s.conflicts[id]);assert.equal(s.tasks[0].start,'2054-10-01');});
