import {test} from 'node:test';
import assert from 'node:assert/strict';
import {seed} from '../seed.mjs';
import {migrate,filterTasks,projectSummary,operationsCategories} from '../portfolio.mjs';
import {edit,risk,sync,MockCalendar} from '../core.mjs';
function fixture(){const s=migrate(seed());s.tasks.push({...structuredClone(s.tasks[0]),id:'ops-support',project:'atlas-ops',title:'Support fixture',lane:s.projects.find(p=>p.id==='atlas-ops').lanes[0],assignee:'Ops Agent',status:'DOING',start:'2054-09-29',end:'2054-10-01',remaining:1,blocker:'Awaiting response',decision:'',dependencies:[],milestoneId:'',category:'support/inquiries',cadence:'weekly',sample:true});return s;}
test('migration is idempotent, preserves existing task edits, calendar IDs, queue and audit',()=>{const s=seed();edit(s,'atlas-sample-1',{title:'Edited title'});sync(s,new MockCalendar(s.events));const before=structuredClone(s);const n=migrate(s);assert.deepEqual(s,before);assert.equal(n.tasks[0].title,'Edited title');assert.deepEqual(n.events,before.events);assert.deepEqual(n.links,before.links);assert.deepEqual(n.queue,before.queue);assert.deepEqual(n.audit.slice(0,-1),before.audit);assert.deepEqual(migrate(n),n);assert.equal(n.projects.filter(p=>p.id==='atlas-ops').length,1);assert.equal(n.projects.find(p=>p.id==='atlas-ops').active,false);assert.equal(n.tasks[0].milestoneId,'atlas-release');assert.equal(n.revision,s.revision+1);});
test('portfolio filters span projects and combine all predicates with inclusive interval overlap',()=>{const s=fixture(),date='2054-09-30';assert.equal(filterTasks(s).length,6);assert.deepEqual(filterTasks(s,{stream:'operations'}).map(t=>t.id),['ops-support']);const f={project:'atlas-ops',lane:'運用チーム · 未割当',assignee:'Ops Agent',status:'DOING',attention:'blocked',risk:'watch',from:'2054-10-01',to:'2054-10-01'};assert.deepEqual(filterTasks(s,f,date).map(t=>t.id),['ops-support']);assert.equal(filterTasks(s,{...f,to:'2054-09-30'},date).length,0);assert.equal(filterTasks(s,{...f,from:'2054-10-02',to:'2054-10-02'},date).length,0);assert.equal(filterTasks(s,{...f,attention:'decision'},date).length,0);assert.equal(filterTasks(s,{from:'2054-02-30'},date).length,0);assert.equal(filterTasks(s,{status:'REVIEW'},date)[0].project,'atlas');assert.equal(filterTasks(s,{attention:'decision'},date)[0].id,'atlas-sample-1');});
test('summary derives progress only from task states, separates samples and selects nearest deadlines',()=>{const s=fixture(),p=s.projects[0];let x=projectSummary(s,p,s.tasks,'2054-09-30');assert.equal(x.knownTotal,0);assert.equal(x.sampleTotal,4);assert.equal(x.sampleDone,0);assert.equal(x.next.id,'atlas-sample-1');assert.equal(x.milestone.id,'atlas-release');assert.equal(x.doing.length,2);assert.equal(x.decisions.length,1);assert.ok(x.reasons.some(r=>r.reason.includes('ブロッカー')));edit(s,'atlas-sample-1',{status:'DONE'});x=projectSummary(s,p,s.tasks,'2054-09-30');assert.equal(x.sampleDone,1);assert.equal(x.next.id,'atlas-sample-2');const empty=projectSummary(s,s.projects[1],s.tasks,'2054-09-30');assert.equal(empty.level,'unknown');assert.equal(empty.next,null);assert.equal(empty.knownTotal,0);});
test('hierarchy constrains milestone links by project and applies only the linked milestone deadline',()=>{const s=fixture();assert.throws(()=>edit(s,'ops-support',{milestoneId:'atlas-release'}),/milestone/);assert.throws(()=>edit(s,'atlas-release',{milestoneId:'atlas-release'}),/milestone/);assert.throws(()=>edit(s,'atlas-sample-1',{milestoneId:'atlas-sample-2'}),/milestone/);edit(s,'atlas-sample-1',{end:'2054-11-03'});assert.ok(risk(s.tasks[0],s.tasks,'2054-09-30').reasons.includes('リリース目標を超過'));edit(s,'atlas-sample-1',{milestoneId:''});assert.ok(!risk(s.tasks[0],s.tasks,'2054-09-30').reasons.includes('リリース目標を超過'));});
test('operations categories and cadence are editable metadata without recurring duplicates or live calls',()=>{const s=fixture();assert.equal(operationsCategories.length,6);edit(s,'ops-support',{category:'incidents',cadence:'as-needed'});assert.equal(s.tasks.at(-1).category,'incidents');assert.equal(s.tasks.length,6);assert.throws(()=>edit(s,'ops-support',{category:'unrecognized'}));assert.throws(()=>edit(s,'ops-support',{cadence:'hourly'}));assert.throws(()=>edit(s,'atlas-sample-1',{category:'incidents'}));const a=new MockCalendar(s.events),unrelated=structuredClone(s.events['unrelated-event']);sync(s,a);sync(s,a);assert.deepEqual(s.events['unrelated-event'],unrelated);assert.equal(s.tasks.length,6);});
test('future development versions remain independent projects in the same portfolio/family',()=>{const s=fixture();s.projects.push({id:'atlas-v2',name:'Atlas v2',portfolio:'hibou',family:'Atlas',stream:'development',lanes:['v2 team'],active:false});s.tasks.push({...structuredClone(s.tasks[0]),id:'v2-task',project:'atlas-v2',lane:'v2 team',milestoneId:'',end:'2055-01-01'});const [t]=filterTasks(s,{project:'atlas-v2'});assert.equal(t.id,'v2-task');assert.ok(!risk(t,s.tasks,'2054-09-30').reasons.includes('リリース目標を超過'));assert.equal(filterTasks(s,{stream:'operations'}).length,1);});
